[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    4-20ma/ModbusMaster @ ^2.0.1

monitor_filters = time, printable

; -------------------------------------------------------------------
; PROFIL 1: ULTRASCHALL-SENSOR
; -------------------------------------------------------------------
[env:zisterne_ultraschall]
build_flags = 
    -D FIRMWARE_VERSION=32
    -D IS_ULTRASCHALL=1

upload_protocol = esptool
upload_port = /dev/ttyUSB4
monitor_port = /dev/ttyUSB4

; -------------------------------------------------------------------
; PROFIL 2: RADAR-SENSOR
; -------------------------------------------------------------------
[env:zisterne_radar]
build_flags = 
    -D FIRMWARE_VERSION=32
    -D IS_RADAR=1

upload_protocol = esptool
upload_port = /dev/ttyUSB5
monitor_port = /dev/ttyUSB5
