[env:esp32-s3-devkitc-1]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

;monitor_filters = esp32_exception_decoder, time
monitor_filters = time, printable

lib_deps =
    bblanchon/ArduinoJson

build_flags =
    -DCORE_DEBUG_LEVEL=3

upload_protocol = esptool
upload_port = /dev/ttyESPNowGateway
monitor_port = /dev/ttyESPNowGateway

extra_scripts = pre:toggle_service.py
