[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    bblanchon/ArduinoJson @ ^7.0.0
    4-20ma/ModbusMaster @ ^2.0.1

build_flags =
    -D FIRMWARE_VERSION=31

upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
